cache:
  paths:
    - .m2/repository

stages:
- build
- test

.build: &build
  stage: build
  script:
    - 'mvn dependency:go-offline'

.test: &test
  stage: test
  script:
    - 'mvn org.jacoco:jacoco-maven-plugin:prepare-agent install -Pcoverage-per-test'
  
  cache:
    paths:
      - /builds/coteafs/dataset/target/
      - /builds/coteafs/dataset/reports/

build:
  <<: *build
  image: maven:3.3.9-jdk-8

test:
  <<: *test
  image: maven:3.3.9-jdk-8